import express from 'express';
import {requireAuth,requireRole} from '../middleware/auth.js';
import {AIMessage,RiskFlag,CrisisContact,CareSummary,CheckIn,Assignment} from '../models/index.js';
import {analyseText,safeFirstResponse} from '../services/riskService.js';
import {determineCareState} from '../services/orchestratorService.js';
import {getListenerReply,generateCareSummary} from '../services/aiService.js';
import {encryptText,decryptText} from '../utils/crypto.js';
const router=express.Router();
router.use('/listener',requireAuth,requireRole('user'));
router.use('/api/ai',requireAuth,requireRole('user'));
router.get('/listener',async(req,res)=>{const rows=await AIMessage.findAll({where:{userId:req.user.id},order:[['createdAt','ASC']],limit:60});const messages=rows.map(m=>({...m.toJSON(),content:decryptText(m.encryptedContent)}));res.render('ai/listener',{title:'AI Emotional Listener',messages,aiEnabled:Boolean(process.env.OPENAI_API_KEY)});});
router.post('/api/ai/listen',async(req,res)=>{const message=String(req.body.message||'').trim().slice(0,5000);if(!message)return res.status(400).json({error:'Please write something first.'});const analysis=analyseText(message);const orchestrated=determineCareState({riskLevel:analysis.riskLevel,emotion:analysis.emotion,capacity:req.user.capacity});await AIMessage.create({userId:req.user.id,sender:'user',encryptedContent:encryptText(message),emotion:analysis.emotion,riskLevel:analysis.riskLevel,themes:analysis.themes});if(analysis.riskLevel==='high'||analysis.riskLevel==='crisis'){const assignment=await Assignment.findOne({where:{userId:req.user.id,active:true,isPrimary:true}});await RiskFlag.create({userId:req.user.id,source:'ai_listener',excerpt:message.slice(0,500),riskLevel:analysis.riskLevel,status:'open',therapistNotifiedAt:assignment?new Date():null});await req.user.update({therapeuticMode:orchestrated.mode});const firstResponse=safeFirstResponse(analysis.riskLevel);await AIMessage.create({userId:req.user.id,sender:'ai',encryptedContent:encryptText(firstResponse),emotion:analysis.emotion,riskLevel:analysis.riskLevel,themes:analysis.themes});const contacts=await CrisisContact.findAll({where:{active:true},order:[['priority','ASC']],limit:6});return res.json({reply:firstResponse,state:orchestrated,crisisBridge:true,contacts:contacts.map(c=>({name:c.name,phone:c.phone,website:c.website,region:c.region}))});}
const recentRows=await AIMessage.findAll({where:{userId:req.user.id},order:[['createdAt','DESC']],limit:10});const recentMessages=recentRows.reverse().map(m=>({...m.toJSON(),content:decryptText(m.encryptedContent)}));const reply=await getListenerReply({message,user:req.user,analysis,recentMessages});await AIMessage.create({userId:req.user.id,sender:'ai',encryptedContent:encryptText(reply),emotion:analysis.emotion,riskLevel:analysis.riskLevel,themes:analysis.themes});const messageCount=await AIMessage.count({where:{userId:req.user.id}});if(messageCount>0&&messageCount%10===0){const messages=(await AIMessage.findAll({where:{userId:req.user.id},order:[['createdAt','ASC']],limit:20})).map(m=>({...m.toJSON(),content:decryptText(m.encryptedContent)}));const checkIns=await CheckIn.findAll({where:{userId:req.user.id},order:[['createdAt','DESC']],limit:10});const summary=await generateCareSummary({messages,checkIns,user:req.user});await CareSummary.create({userId:req.user.id,summary,periodStart:messages[0]?.createdAt||new Date(),periodEnd:new Date()});}res.json({reply,state:orchestrated,crisisBridge:false});});
export default router;
