import express from 'express';
import {requireAuth,requireRole} from '../middleware/auth.js';
import {JournalEntry,RiskFlag,Assignment} from '../models/index.js';
import {analyseText,safeFirstResponse} from '../services/riskService.js';
import {generateJournalReflection} from '../services/aiService.js';
import {encryptText,decryptText} from '../utils/crypto.js';
const router=express.Router();router.use(requireAuth,requireRole('user'));
router.get('/mindfulness',async(req,res)=>{const entries=await JournalEntry.findAll({where:{userId:req.user.id},order:[['createdAt','DESC']],limit:12});res.render('mindfulness/index',{title:'Mindfulness Corner',entries:entries.map(e=>({...e.toJSON(),content:decryptText(e.encryptedContent)}))});});
router.post('/mindfulness/journal',async(req,res)=>{const content=String(req.body.content||'').trim().slice(0,8000);if(!content){req.session.notice={type:'warning',text:'Your journal can stay empty until there is something you want to place there.'};return res.redirect('/mindfulness');}const analysis=analyseText(content);let reflection='';if(['high','crisis'].includes(analysis.riskLevel)){const assignment=await Assignment.findOne({where:{userId:req.user.id,active:true,isPrimary:true}});await RiskFlag.create({userId:req.user.id,source:'journal',excerpt:content.slice(0,500),riskLevel:analysis.riskLevel,status:'open',therapistNotifiedAt:assignment?new Date():null});reflection=safeFirstResponse(analysis.riskLevel);}else{reflection=await generateJournalReflection({entry:content,user:req.user});}await JournalEntry.create({userId:req.user.id,type:req.body.type||'reflection',encryptedContent:encryptText(content),aiReflection:reflection,mood:Math.max(1,Math.min(5,Number(req.body.mood||3))),themes:analysis.themes});req.session.notice={type:'success',text:'Journal saved. The reflective mirror is available below it.'};res.redirect('/mindfulness');});
export default router;
