import express from 'express';
import {Op} from 'sequelize';
import {Assignment,User,CheckIn,CareSummary,RiskFlag,SOAPNote,CarePlan,SessionBooking,DirectMessage,JournalEntry,RoomSession,AuditLog} from '../models/index.js';
import {requireAuth,requireRole} from '../middleware/auth.js';
import {encryptText,decryptText} from '../utils/crypto.js';
const router=express.Router();router.use(requireAuth,requireRole('therapist'));
async function assignedClient(therapistId,clientId){const assignment=await Assignment.findOne({where:{therapistId,userId:clientId,active:true},include:[{model:User,as:'client'}]});return assignment?.client||null;}
router.get('/therapist',async(req,res)=>{const assignments=await Assignment.findAll({where:{therapistId:req.user.id,active:true},include:[{model:User,as:'client',attributes:['id','name','email','therapeuticMode','capacity','lastSeenAt']}]});const clientIds=assignments.map(a=>a.userId);const riskFlags=clientIds.length?await RiskFlag.findAll({where:{userId:{[Op.in]:clientIds},status:{[Op.in]:['open','acknowledged','escalated']}},include:[{model:User,attributes:['id','name']}],order:[['createdAt','DESC']],limit:20}):[];const bookings=await SessionBooking.findAll({where:{therapistId:req.user.id},include:[{model:User,as:'client',attributes:['id','name']}],order:[['scheduledAt','ASC']],limit:20});res.render('therapist/dashboard',{title:'Therapist Corner',assignments,riskFlags,bookings});});
router.get('/therapist/users/:id',async(req,res)=>{const client=await assignedClient(req.user.id,req.params.id);if(!client)return res.status(404).render('error',{title:'Not assigned',message:'This user is not in your active caseload.'});const[checkIns,summaries,flags,notes,plans,journals,roomSessions]=await Promise.all([CheckIn.findAll({where:{userId:client.id},order:[['createdAt','DESC']],limit:20}),CareSummary.findAll({where:{userId:client.id},order:[['createdAt','DESC']],limit:10}),RiskFlag.findAll({where:{userId:client.id},order:[['createdAt','DESC']],limit:20}),SOAPNote.findAll({where:{userId:client.id,therapistId:req.user.id},order:[['createdAt','DESC']],limit:10}),CarePlan.findAll({where:{userId:client.id,therapistId:req.user.id},order:[['updatedAt','DESC']],limit:5}),JournalEntry.findAll({where:{userId:client.id},order:[['createdAt','DESC']],limit:10}),RoomSession.findAll({where:{userId:client.id},order:[['createdAt','DESC']],limit:20})]);res.render('therapist/user',{title:client.name,client,checkIns,summaries,flags,notes:notes.map(n=>({...n.toJSON(),subjective:decryptText(n.subjective),objective:decryptText(n.objective),assessment:decryptText(n.assessment),plan:decryptText(n.plan)})),plans,roomSessions,journals:client.transcriptSharing?journals.map(j=>({...j.toJSON(),content:decryptText(j.encryptedContent)})):[]});});
router.post('/therapist/users/:id/soap',async(req,res)=>{const client=await assignedClient(req.user.id,req.params.id);if(!client)return res.sendStatus(403);await SOAPNote.create({userId:client.id,therapistId:req.user.id,subjective:encryptText(String(req.body.subjective||'').slice(0,5000)),objective:encryptText(String(req.body.objective||'').slice(0,5000)),assessment:encryptText(String(req.body.assessment||'').slice(0,5000)),plan:encryptText(String(req.body.plan||'').slice(0,5000))});req.session.notice={type:'success',text:'SOAP note saved to the clinical workspace.'};res.redirect(`/therapist/users/${client.id}`);});
router.post('/therapist/users/:id/care-plan',async(req,res)=>{const client=await assignedClient(req.user.id,req.params.id);if(!client)return res.sendStatus(403);const split=v=>String(v||'').split('\n').map(x=>x.trim()).filter(Boolean);await CarePlan.create({userId:client.id,therapistId:req.user.id,goals:split(req.body.goals),warningSigns:split(req.body.warningSigns),preferences:split(req.body.preferences),nextActions:split(req.body.nextActions),status:'active'});req.session.notice={type:'success',text:'Care plan saved.'};res.redirect(`/therapist/users/${client.id}`);});
router.post('/therapist/summaries/:id/review',async(req,res)=>{const summary=await CareSummary.findByPk(req.params.id);if(!summary)return res.sendStatus(404);const client=await assignedClient(req.user.id,summary.userId);if(!client)return res.sendStatus(403);await summary.update({clinicianCorrection:String(req.body.clinicianCorrection||'').slice(0,5000),reviewedById:req.user.id,reviewedAt:new Date()});await AuditLog.create({actorId:req.user.id,action:'ai_summary_reviewed',targetType:'CareSummary',targetId:summary.id,details:{clientId:client.id}});res.redirect(`/therapist/users/${client.id}`);});
router.get('/therapist/messages/:id',async(req,res)=>{const client=await assignedClient(req.user.id,req.params.id);if(!client)return res.sendStatus(403);const rows=await DirectMessage.findAll({where:{[Op.or]:[{senderId:req.user.id,recipientId:client.id},{senderId:client.id,recipientId:req.user.id}]},order:[['createdAt','ASC']],limit:200});const messages=rows.map(m=>({...m.toJSON(),content:decryptText(m.encryptedContent)}));res.render('therapist/messages',{title:`Messages - ${client.name}`,client,messages});});
router.post('/therapist/messages/:id',async(req,res)=>{const client=await assignedClient(req.user.id,req.params.id);if(!client)return res.sendStatus(403);await DirectMessage.create({senderId:req.user.id,recipientId:client.id,encryptedContent:encryptText(String(req.body.message||'').slice(0,5000)),messageType:'text'});res.redirect(`/therapist/messages/${client.id}`);});
router.post('/therapist/bookings/:id/status',async(req,res)=>{const booking=await SessionBooking.findOne({where:{id:req.params.id,therapistId:req.user.id}});if(!booking)return res.sendStatus(404);const allowed=['confirmed','completed','cancelled'];if(allowed.includes(req.body.status))await booking.update({status:req.body.status});res.redirect('/therapist');});
export default router;
