import OpenAI from 'openai';
let client=null;
function getClient(){if(!process.env.OPENAI_API_KEY)return null;if(!client)client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});return client;}
function clean(text){return String(text||'').trim();}
function fallbackReply({message,emotion,capacity}){
  const value=clean(message); if(!value)return 'I am here. You do not need to fill the silence.';
  if(emotion==='anxious'||emotion==='overwhelmed')return capacity==='not_much'?'That sounds like a lot to carry with very little capacity. We can keep this small. Would you prefer one slow breath, a grounding room, or quiet company?':'I can hear the pressure in what you wrote. We do not have to solve everything at once. What feels most present in your body right now?';
  if(emotion==='grieving')return 'I hear the weight of the loss in what you shared. I will not rush you toward feeling better. If it feels right, you can tell me what you miss most, or we can stay quiet.';
  if(emotion==='drained')return 'You sound tired rather than in need of another task. Rest can count as support here. Would you like me to keep this brief and open The Long Afternoon?';
  if(emotion==='lonely')return 'Feeling unwitnessed can be heavy. I am here with what you wrote. You can keep talking, or leave a quiet lantern for someone else to find.';
  if(emotion==='numb')return 'Numbness can make even simple questions feel like too much. We can stay with what is here without forcing meaning. Would a sensory grounding prompt help?';
  return 'I am listening. You do not have to make this neat or productive. Tell me only what feels possible to say right now.';
}
async function callModel({instructions,input}){const openai=getClient();if(!openai)return null;try{const response=await openai.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.6',instructions,input});return clean(response.output_text);}catch(error){console.error('AI provider error:',error.message);return null;}}
export async function getListenerReply({message,user,analysis,recentMessages=[]}){
  const history=recentMessages.slice(-8).map(m=>`${m.sender==='user'?'User':'Chiedza'}: ${m.content}`).join('\n');
  const instructions=`You are the AI Emotional Listener inside Chiedza. You are NOT a therapist and must never claim to diagnose, treat, cure, or replace a licensed professional. Your role is listener, reflector, and sensor. Be gentle, culturally respectful, non-judgmental, and concise. Do not use streaks, guilt, urgency, engagement tricks, or motivational pressure. Do not tell the user that a feeling is definitely caused by a condition. If the user seems distressed, reduce language and offer one manageable choice. Never provide methods for self-harm. Crisis/high-risk content is handled before this call by the human-safeguarding bridge. User language preference: ${user.language||'en'}. Cultural context: ${user.culture||'not specified'}. Faith preference: ${user.faith||'none/unspecified'}. Current capacity: ${user.capacity||'some'}. Detected emotional signal: ${analysis.emotion}. Respond in 1-3 short paragraphs and at most one gentle question.`;
  const ai=await callModel({instructions,input:`${history?`Recent context:\n${history}\n\n`:''}User: ${message}`});
  return ai||fallbackReply({message,emotion:analysis.emotion,capacity:user.capacity});
}
export async function generateJournalReflection({entry,user}){const instructions=`You are Chiedza's AI Reflective Mirror. Summarise emotional patterns gently without diagnosis. Use the user's own themes where possible. Do not over-interpret. Do not give clinical treatment advice. Keep the reflection under 120 words. Cultural context: ${user.culture||'not specified'}; language preference: ${user.language||'en'}.`;return await callModel({instructions,input:entry})||'What you wrote carries a few layers at once. Rather than forcing a conclusion, notice which sentence still feels alive when you read it back. That may be enough for today.';}
export async function generatePoem({prompt,user,format='free verse'}){const instructions=`Create a gentle ${format} poem for Chiedza based only on the user's supplied emotional themes. Avoid diagnosis, promises of recovery, or romanticising crisis. Keep it reflective, culturally respectful, and under 180 words. Language preference: ${user.language||'en'}; culture: ${user.culture||'not specified'}.`;return await callModel({instructions,input:prompt})||`A small light stays,\nnot because the night is gone,\nbut because you are still here.\n\nNo need to hurry the morning.\nLet the next breath be enough.`;}
export async function generateCareSummary({messages,checkIns,user}){
  const transcript=messages.slice(-20).map(m=>`${m.sender}: ${m.content}`).join('\n'); const checkinText=checkIns.slice(0,10).map(c=>`mood ${c.mood}/5, capacity ${c.capacity}, note ${c.note||'-'}`).join('\n');
  const instructions='You are a clinical support summarisation engine, not a clinician. Create a concise structured summary for a licensed therapist to REVIEW. Do not diagnose. Separate observed user statements from inference. Return plain text with headings: Emotional timeline; Key themes; Distress triggers; Coping signals; Risk indicators; Behavioural patterns; Review note. Always end Review note with: "AI-generated summary - clinician review required."';
  const ai=await callModel({instructions,input:`User context: language=${user.language}, culture=${user.culture}\n\nRecent chat:\n${transcript}\n\nRecent check-ins:\n${checkinText}`}); if(ai)return ai;
  const themes=[...new Set(messages.flatMap(m=>m.themes||[]))]; return `Emotional timeline: Recent interactions available for review.\nKey themes: ${themes.length?themes.join(', '):'No repeated theme detected yet'}.\nDistress triggers: Not enough structured evidence yet.\nCoping signals: Room use and check-ins should be reviewed alongside this summary.\nRisk indicators: Review any open safeguarding flags.\nBehavioural patterns: More longitudinal data required.\nReview note: AI-generated summary - clinician review required.`;
}
