const copy = {
  en: {arrival:'Take a breath. There is no rush. This app does not need you to perform.',consent:'We will not sell your data. We will not message you with guilt.',capacity:'How much do you have today?',routing:'What kind of care do you need right now?',welcomeBack:'Welcome back. We kept your place.'},
  sn: {arrival:'Tora mweya zvinyoronyoro. Hapana kukurumidza. Hapana chaunofanira kuratidza pano.',consent:'Hatitengesi ruzivo rwako uye hatitumiri mameseji ekukumanikidza.',capacity:'Simba rako riri papi nhasi?',routing:'Rudzii rwerutsigiro rwaunoda izvozvi?',welcomeBack:'Wauya zvakare. Takachengeta nzvimbo yako.'},
  xh: {arrival:'Phefumla kancinci. Akukho kungxama. Le app ayifuni ukuba wenze ngathi ulungile.',consent:'Asiyi kuthengisa iinkcukacha zakho okanye sikuthumele imiyalezo ekukuhlaziseni.',capacity:'Unamandla angakanani namhlanje?',routing:'Loluphi uhlobo lwenkxaso oludingayo ngoku?',welcomeBack:'Wamkelekile kwakhona. Sikugcinele indawo yakho.'},
  zu: {arrival:'Phefumula kancane. Akukho ukushesha. Lolu hlelo aludingi ukuthi uzenze sengathi ulungile.',consent:'Ngeke sidayise imininingwane yakho noma sikuthumele imiyalezo yokukuhlazisa.',capacity:'Unamandla angakanani namuhla?',routing:'Hlobo luni losizo oludingayo manje?',welcomeBack:'Siyakwamukela futhi. Sikugcinele indawo yakho.'},
  af: {arrival:'Haal rustig asem. Daar is geen haas nie. Hierdie toepassing vra nie dat jy moet presteer nie.',consent:'Ons sal nie jou data verkoop of skuldboodskappe stuur nie.',capacity:'Hoeveel kapasiteit het jy vandag?',routing:'Watter soort ondersteuning het jy nou nodig?',welcomeBack:'Welkom terug. Ons het jou plek gehou.'},
  yo: {arrival:'Mí díẹ̀. Kò sí ìkánjú. Ìṣàfilọ́lẹ̀ yìí kò fẹ́ kí o ṣe bí ẹni pé ohun gbogbo dára.',consent:'A kì í ta data rẹ, a kì í sì fi ìtìjú ránṣẹ́ sí ọ.',capacity:'Agbara mélòó ni o ní lónìí?',routing:'Irú ìtìlẹ́yìn wo ni o nílò báyìí?',welcomeBack:'Káàbọ̀ padà. A pa àyè rẹ mọ́.'}
};
export function t(language,key){return copy[language]?.[key]||copy.en[key]||key;}
export const supportedLanguages=[{code:'en',label:'English'},{code:'sn',label:'Shona'},{code:'xh',label:'isiXhosa'},{code:'zu',label:'isiZulu'},{code:'af',label:'Afrikaans'},{code:'yo',label:'Yoruba'}];
