import {DataTypes} from 'sequelize';
import sequelize from '../config/database.js';

export const User=sequelize.define('User',{name:{type:DataTypes.STRING,allowNull:false},email:{type:DataTypes.STRING,allowNull:false,unique:true},passwordHash:{type:DataTypes.STRING,allowNull:false},role:{type:DataTypes.ENUM('user','therapist','reviewer','admin'),allowNull:false,defaultValue:'user'},language:{type:DataTypes.STRING,defaultValue:'en'},culture:{type:DataTypes.STRING,defaultValue:''},faith:{type:DataTypes.STRING,defaultValue:''},timezone:{type:DataTypes.STRING,defaultValue:'Africa/Harare'},communicationPreference:{type:DataTypes.STRING,defaultValue:'chat'},therapeuticMode:{type:DataTypes.ENUM('stabilisation','active','recovery','crisis'),defaultValue:'recovery'},capacity:{type:DataTypes.ENUM('little','some','not_much','unknown'),defaultValue:'some'},aiOnlyMode:{type:DataTypes.BOOLEAN,defaultValue:false},therapistVisibility:{type:DataTypes.BOOLEAN,defaultValue:true},transcriptSharing:{type:DataTypes.BOOLEAN,defaultValue:false},recordingConsent:{type:DataTypes.BOOLEAN,defaultValue:false},contactConsent:{type:DataTypes.BOOLEAN,defaultValue:true},lowBatteryMode:{type:DataTypes.BOOLEAN,defaultValue:false},reducedMotion:{type:DataTypes.BOOLEAN,defaultValue:false},preferredTherapistGender:{type:DataTypes.STRING,defaultValue:''},needs:{type:DataTypes.JSON,defaultValue:[]},onboardingComplete:{type:DataTypes.BOOLEAN,defaultValue:false},isActive:{type:DataTypes.BOOLEAN,defaultValue:true},lastSeenAt:{type:DataTypes.DATE,allowNull:true}});
export const TherapistProfile=sequelize.define('TherapistProfile',{qualifications:{type:DataTypes.TEXT,defaultValue:''},specialties:{type:DataTypes.JSON,defaultValue:[]},languages:{type:DataTypes.JSON,defaultValue:['en']},gender:{type:DataTypes.STRING,defaultValue:''},faithAlignment:{type:DataTypes.STRING,defaultValue:''},therapyStyle:{type:DataTypes.STRING,defaultValue:'integrative'},crisisCapability:{type:DataTypes.BOOLEAN,defaultValue:false},acceptingNewClients:{type:DataTypes.BOOLEAN,defaultValue:true},workloadLimit:{type:DataTypes.INTEGER,defaultValue:20},availability:{type:DataTypes.JSON,defaultValue:{}},timezone:{type:DataTypes.STRING,defaultValue:'Africa/Harare'}});
export const Assignment=sequelize.define('Assignment',{active:{type:DataTypes.BOOLEAN,defaultValue:true},matchScore:{type:DataTypes.FLOAT,defaultValue:0},isPrimary:{type:DataTypes.BOOLEAN,defaultValue:true}});
export const CheckIn=sequelize.define('CheckIn',{mood:{type:DataTypes.INTEGER,allowNull:false,defaultValue:3},capacity:{type:DataTypes.STRING,defaultValue:'some'},state:{type:DataTypes.STRING,defaultValue:'Stable'},note:{type:DataTypes.TEXT,defaultValue:''},emotion:{type:DataTypes.STRING,defaultValue:'calm'},riskLevel:{type:DataTypes.STRING,defaultValue:'low'}});
export const AIMessage=sequelize.define('AIMessage',{sender:{type:DataTypes.ENUM('user','ai'),allowNull:false},encryptedContent:{type:DataTypes.TEXT,allowNull:false},emotion:{type:DataTypes.STRING,defaultValue:'calm'},riskLevel:{type:DataTypes.STRING,defaultValue:'low'},themes:{type:DataTypes.JSON,defaultValue:[]},providerResponseId:{type:DataTypes.STRING,allowNull:true}});
export const CareSummary=sequelize.define('CareSummary',{summary:{type:DataTypes.TEXT,allowNull:false},periodStart:{type:DataTypes.DATE,allowNull:true},periodEnd:{type:DataTypes.DATE,allowNull:true},clinicianCorrection:{type:DataTypes.TEXT,defaultValue:''},reviewedAt:{type:DataTypes.DATE,allowNull:true}});
export const RiskFlag=sequelize.define('RiskFlag',{source:{type:DataTypes.STRING,defaultValue:'ai_listener'},excerpt:{type:DataTypes.TEXT,defaultValue:''},riskLevel:{type:DataTypes.ENUM('moderate','high','crisis'),defaultValue:'moderate'},status:{type:DataTypes.ENUM('open','acknowledged','escalated','closed'),defaultValue:'open'},reviewerNotes:{type:DataTypes.TEXT,defaultValue:''},actionTaken:{type:DataTypes.TEXT,defaultValue:''},therapistNotifiedAt:{type:DataTypes.DATE,allowNull:true}});
export const JournalEntry=sequelize.define('JournalEntry',{type:{type:DataTypes.ENUM('night','release','reflection'),defaultValue:'reflection'},encryptedContent:{type:DataTypes.TEXT,allowNull:false},aiReflection:{type:DataTypes.TEXT,defaultValue:''},mood:{type:DataTypes.INTEGER,defaultValue:3},themes:{type:DataTypes.JSON,defaultValue:[]}});
export const RoomSession=sequelize.define('RoomSession',{room:{type:DataTypes.ENUM('calm','ground','rest','return','carry'),allowNull:false},stateBefore:{type:DataTypes.STRING,defaultValue:''},stateAfter:{type:DataTypes.STRING,defaultValue:''},aftercareCompleted:{type:DataTypes.BOOLEAN,defaultValue:false},details:{type:DataTypes.JSON,defaultValue:{}}});
export const Lantern=sequelize.define('Lantern',{encryptedContent:{type:DataTypes.TEXT,allowNull:false},theme:{type:DataTypes.STRING,defaultValue:'general'},pod:{type:DataTypes.STRING,defaultValue:'global'},moderationStatus:{type:DataTypes.ENUM('pending','approved','rejected'),defaultValue:'pending'},safetyFlag:{type:DataTypes.BOOLEAN,defaultValue:false},publishedAt:{type:DataTypes.DATE,allowNull:true}});
export const SOAPNote=sequelize.define('SOAPNote',{subjective:{type:DataTypes.TEXT,defaultValue:''},objective:{type:DataTypes.TEXT,defaultValue:''},assessment:{type:DataTypes.TEXT,defaultValue:''},plan:{type:DataTypes.TEXT,defaultValue:''}});
export const CarePlan=sequelize.define('CarePlan',{goals:{type:DataTypes.JSON,defaultValue:[]},warningSigns:{type:DataTypes.JSON,defaultValue:[]},preferences:{type:DataTypes.JSON,defaultValue:[]},nextActions:{type:DataTypes.JSON,defaultValue:[]},status:{type:DataTypes.ENUM('active','paused','completed'),defaultValue:'active'}});
export const SessionBooking=sequelize.define('SessionBooking',{type:{type:DataTypes.ENUM('video','audio','chat'),defaultValue:'chat'},scheduledAt:{type:DataTypes.DATE,allowNull:false},status:{type:DataTypes.ENUM('requested','confirmed','completed','cancelled'),defaultValue:'requested'},notes:{type:DataTypes.TEXT,defaultValue:''}});
export const DirectMessage=sequelize.define('DirectMessage',{encryptedContent:{type:DataTypes.TEXT,allowNull:false},messageType:{type:DataTypes.ENUM('text','voice'),defaultValue:'text'},mediaPath:{type:DataTypes.STRING,allowNull:true}});
export const Milestone=sequelize.define('Milestone',{title:{type:DataTypes.STRING,allowNull:false},note:{type:DataTypes.TEXT,defaultValue:''},happenedAt:{type:DataTypes.DATE,defaultValue:DataTypes.NOW},stoneType:{type:DataTypes.STRING,defaultValue:'healing'}});
export const CrisisContact=sequelize.define('CrisisContact',{region:{type:DataTypes.STRING,defaultValue:'Global'},countryCode:{type:DataTypes.STRING,defaultValue:''},name:{type:DataTypes.STRING,allowNull:false},phone:{type:DataTypes.STRING,defaultValue:''},website:{type:DataTypes.STRING,defaultValue:''},priority:{type:DataTypes.INTEGER,defaultValue:100},active:{type:DataTypes.BOOLEAN,defaultValue:true},verifiedAt:{type:DataTypes.DATE,allowNull:true}});
export const Subscription=sequelize.define('Subscription',{plan:{type:DataTypes.ENUM('free','plus','corporate','pathway_youth'),defaultValue:'free'},status:{type:DataTypes.ENUM('active','trial','paused','cancelled'),defaultValue:'active'},renewsAt:{type:DataTypes.DATE,allowNull:true}});
export const AuditLog=sequelize.define('AuditLog',{action:{type:DataTypes.STRING,allowNull:false},targetType:{type:DataTypes.STRING,defaultValue:''},targetId:{type:DataTypes.INTEGER,allowNull:true},details:{type:DataTypes.JSON,defaultValue:{}}});

User.hasOne(TherapistProfile,{foreignKey:'userId',as:'therapistProfile',onDelete:'CASCADE'}); TherapistProfile.belongsTo(User,{foreignKey:'userId',as:'user'});
Assignment.belongsTo(User,{foreignKey:'userId',as:'client'}); Assignment.belongsTo(User,{foreignKey:'therapistId',as:'therapist'}); User.hasMany(Assignment,{foreignKey:'userId',as:'therapistAssignments'}); User.hasMany(Assignment,{foreignKey:'therapistId',as:'clientAssignments'});
for(const model of [CheckIn,AIMessage,CareSummary,RiskFlag,JournalEntry,RoomSession,Lantern,Milestone,Subscription]){User.hasMany(model,{foreignKey:'userId'});model.belongsTo(User,{foreignKey:'userId'});}
CareSummary.belongsTo(User,{foreignKey:'reviewedById',as:'reviewer'}); RiskFlag.belongsTo(User,{foreignKey:'reviewerId',as:'reviewer'});
SOAPNote.belongsTo(User,{foreignKey:'userId',as:'client'}); SOAPNote.belongsTo(User,{foreignKey:'therapistId',as:'therapist'});
CarePlan.belongsTo(User,{foreignKey:'userId',as:'client'}); CarePlan.belongsTo(User,{foreignKey:'therapistId',as:'therapist'});
SessionBooking.belongsTo(User,{foreignKey:'userId',as:'client'}); SessionBooking.belongsTo(User,{foreignKey:'therapistId',as:'therapist'});
DirectMessage.belongsTo(User,{foreignKey:'senderId',as:'sender'}); DirectMessage.belongsTo(User,{foreignKey:'recipientId',as:'recipient'});
AuditLog.belongsTo(User,{foreignKey:'actorId',as:'actor'});
export async function syncDatabase(options={}){await sequelize.sync(options);} export {sequelize};
