import 'dotenv/config';
import bcrypt from 'bcryptjs';
import {syncDatabase,User,TherapistProfile,Assignment,Subscription,CheckIn,Milestone,CrisisContact,Lantern,CareSummary} from './models/index.js';
import {encryptText} from './utils/crypto.js';
const password='Demo123!';const passwordHash=await bcrypt.hash(password,12);await syncDatabase();
async function upsertUser(email,data){const[user]=await User.findOrCreate({where:{email},defaults:{...data,email,passwordHash}});await user.update({...data,passwordHash});await Subscription.findOrCreate({where:{userId:user.id},defaults:{plan:'free',status:'active'}});return user;}
const demoUser=await upsertUser('user@chiedza.local',{name:'Tariro Demo',role:'user',language:'en',culture:'Zimbabwean',faith:'',capacity:'some',needs:['anxiety','burnout'],onboardingComplete:true,therapistVisibility:true,transcriptSharing:true});
const therapist=await upsertUser('therapist@chiedza.local',{name:'Dr. Nyasha Moyo',role:'therapist',onboardingComplete:true});
const[profile]=await TherapistProfile.findOrCreate({where:{userId:therapist.id},defaults:{qualifications:'Licensed counsellor - demo profile',specialties:['anxiety','burnout','grief','trauma'],languages:['en','sn'],gender:'female',therapyStyle:'integrative',crisisCapability:true,workloadLimit:20,timezone:'Africa/Harare'}});await profile.update({qualifications:'Licensed counsellor - demo profile',specialties:['anxiety','burnout','grief','trauma'],languages:['en','sn'],gender:'female',therapyStyle:'integrative',crisisCapability:true,workloadLimit:20,timezone:'Africa/Harare'});
await upsertUser('reviewer@chiedza.local',{name:'Care Reviewer',role:'reviewer',onboardingComplete:true});await upsertUser('admin@chiedza.local',{name:'Chiedza Administrator',role:'admin',onboardingComplete:true});
const[assignment]=await Assignment.findOrCreate({where:{userId:demoUser.id,therapistId:therapist.id,isPrimary:true},defaults:{active:true,matchScore:88}});await assignment.update({active:true});
if(await CheckIn.count({where:{userId:demoUser.id}})===0)await CheckIn.bulkCreate([{userId:demoUser.id,mood:3,capacity:'some',state:'Stable',note:'Trying to take things one day at a time.',emotion:'calm',riskLevel:'low',createdAt:new Date(Date.now()-4*86400000)},{userId:demoUser.id,mood:2,capacity:'little',state:'Struggling',note:'Work felt overwhelming today and I could not switch off.',emotion:'overwhelmed',riskLevel:'moderate',createdAt:new Date(Date.now()-2*86400000)},{userId:demoUser.id,mood:3,capacity:'some',state:'Stable',note:'Slept a little better last night.',emotion:'calm',riskLevel:'low',createdAt:new Date(Date.now()-86400000)}]);
if(await Milestone.count({where:{userId:demoUser.id}})===0)await Milestone.bulkCreate([{userId:demoUser.id,title:'Asked for support',note:'A quiet milestone, not a score.',stoneType:'healing',happenedAt:new Date(Date.now()-6*86400000)},{userId:demoUser.id,title:'Rested without apologising',note:'The Long Afternoon helped me stop pushing.',stoneType:'rest',happenedAt:new Date(Date.now()-3*86400000)}]);
if(await CareSummary.count({where:{userId:demoUser.id}})===0)await CareSummary.create({userId:demoUser.id,summary:`Emotional timeline: Recent check-ins alternate between manageable days and work-related overwhelm.\nKey themes: burnout, anxiety, sleep.\nDistress triggers: Work pressure appears in recent self-report.\nCoping signals: Rest and reduced stimulation were described as useful.\nRisk indicators: No high-risk language in this demo summary.\nBehavioural patterns: More longitudinal data required.\nReview note: AI-generated summary - clinician review required.`});
if(await Lantern.count()===0)await Lantern.bulkCreate([{userId:demoUser.id,encryptedContent:encryptText('I rested today without explaining why. It felt small, but it mattered.'),theme:'burnout',pod:'Zimbabwe',moderationStatus:'approved',publishedAt:new Date(Date.now()-2*86400000)},{userId:demoUser.id,encryptedContent:encryptText('Some grief does not need advice. Sometimes I only need a place to put it down.'),theme:'grief',pod:'global',moderationStatus:'approved',publishedAt:new Date(Date.now()-86400000)}]);
if(await CrisisContact.count()===0)await CrisisContact.bulkCreate([{region:'Demo / Configure before production',countryCode:'',name:'Local emergency service - replace with verified regional number',phone:'CONFIGURE_IN_ADMIN',website:'',priority:1,active:true,verifiedAt:null},{region:'Demo / Configure before production',countryCode:'',name:'Trusted human support contact - configure operational pathway',phone:'CONFIGURE_IN_ADMIN',website:'',priority:2,active:true,verifiedAt:null}]);
console.log('Seed complete.');console.log('Demo accounts (all password Demo123!):');console.log('user@chiedza.local');console.log('therapist@chiedza.local');console.log('reviewer@chiedza.local');console.log('admin@chiedza.local');process.exit(0);
